name: wasteapptest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  http: 1.2.2
  flutter_svg: ^1.0.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.2.1
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.9
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  carousel_slider: ^5.0.0
  flutter_tawk_to_chat: ^0.4.0+1
  google_maps_flutter: ^2.3.0
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  camera: ^0.10.0
  path_provider: ^2.0.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  image: ^4.0.15
  path: ^1.8.3
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0
  qr_flutter: ^4.1.0
  pdf: ^3.8.4
  open_file: ^3.3.2
  mqtt_client: 10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700