name: wasteapptest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  http: 1.2.2
  flutter_svg: ^1.0.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.2.1
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.9
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  flutter_tawk_to_chat: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700